trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: "nodeapp"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"

  - script: |
      cd app
      npm install
    displayName: "Install Node.js dependencies"

  - task: Docker@2
    displayName: "Build Docker image"
    inputs:
      command: build
      repository: $(imageName)
      dockerfile: docker/Dockerfile.node
      tags: |
        $(Build.BuildId)

  - task: Docker@2
    displayName: "Push Docker image to ACR"
    inputs:
      command: push
      repository: $(imageName)
      tags: |
        $(Build.BuildId)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)/k8s-manifest-files"
      artifactName: "manifests"
      publishLocation: "pipeline"
