trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - download: current
    artifact: manifests

  - task: AzureCLI@2
    inputs:
      azureSubscription: "<Your-Service-Connection>"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials \
          --resource-group rg-devops-aks-lab \
          --name aks-devops-lab \
          --overwrite-existing

        kubectl apply -f $(Pipeline.Workspace)/manifests
    displayName: "Deploy to AKS"
